version: '3'
services:
    auction-web:
        image: ankurjainnitrr/auctionsystem
        container_name: auction-web
        networks:
            - app-network
        depends_on:
            - mongodb

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        networks:
            - app-network
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - auction-web

    mongodb:
        container_name: mongodb
        image: mongo:3.1.5
        networks:
            - app-network

    save-swagger:
        image: busybox
        depends_on:
            - auction-web
        volumes:
            - swagger-json:/spec
        command: >
            /bin/sh -c "sleep 15
            && mkdir -p /spec
            && wget -O /spec/swagger.json http://auction-web:9000/swag.json"

    swagger:
        image: swaggerapi/swagger-ui
        expose:
            - 8080
        ports:
            - "8088:8080"
        environment:
            API_URL: "http://localhost:8080/swag.json"
        networks:
            - app-network
        depends_on:
            - save-swagger
        volumes:
            - swagger-json:/spec

volumes:
  swagger-json:

networks:
  app-network:
    driver: bridge
